### ISSUE TITLE
Why use yaml?

### ISSUE THREAD

**Issue by fabianegli** [elixir-proteomics-community/sdrf-pipelines#2]
Is there a good reason to use yaml in the `extended` branch?

Using `yaml` adds a new dependency (pyyaml) to the package. If the data could be adequately represented in JSON or an INI file they could be handled with Python builtins.

If `yaml` is required/desired, pyyaml should be added to the `requirements.txt`.

**Comment by veitveit** [comment]
The parameters for running a data analysis workflows are defined in a yaml file to facilitate manual editing. 

I added the library to the `requirements.txt`  . Thanks for that!
